# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiobooks.AudioBook')),
            ],
            options={
                'ordering': ['file_name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='audiobook',
            name='authors',
            field=models.ManyToManyField(to='audiobooks.Author'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiobooks.Genre'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiobooks.Language'),
        ),
    ]
