# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0004_auto_20170216_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='path to mp3 file'),
        ),
    ]
