# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0005_auto_20170216_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorrentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='audiobook',
            name='to_listen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='torrent_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='torrent_status',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
