# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0005_auto_20170216_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='to_listen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='torrent_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
