# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0006_auto_20170307_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='torrent_status',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
