# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0007_auto_20170307_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='torrent_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
